-- 코드를 작성해주세요
WITH RECURSIVE GEN AS(
    -- FIRST GEN (INITIALIZATION)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- NEXT GEN
    SELECT C.ID, C.PARENT_ID, G.GENERATION +1
    FROM ECOLI_DATA C
    JOIN GEN G
        ON C.PARENT_ID = G.ID
)

SELECT ID
FROM GEN
WHERE GENERATION = 3
ORDER BY ID ASC;