WITH RECURSIVE GEN AS (
    -- INIT
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- NEXT
    SELECT C.ID, C.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN GEN G
        ON C.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA C
    WHERE C.PARENT_ID = G.ID
    )
GROUP BY GENERATION
ORDER BY GENERATION;