/*
1. 입양일의 시간대별로 그룹
2. 시간대별로 정렬, 없는 시간대도 만들어서 0으로 보여줘야함
*/
WITH RECURSIVE HOUR AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR+1 
    FROM HOUR
    WHERE 0 <= HOUR AND HOUR < 23

)


SELECT H.HOUR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN HOUR H
ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;