-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(G.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD G
JOIN USED_GOODS_USER U
ON G.WRITER_ID = U.USER_ID
WHERE G.STATUS="DONE"
GROUP BY U.USER_ID HAVING SUM(G.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;