SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
JOIN ITEM_INFO P
ON P.ITEM_ID = IT.PARENT_ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;