SELECT MONTH(C1.START_DATE) AS MONTH, C1.CAR_ID, COUNT(C1.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
JOIN(
    SELECT CAR_ID, COUNT(*) AS TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID) C2
ON C2.CAR_ID = C1.CAR_ID
WHERE C2.TOTAL >= 5 AND C1.START_DATE >= '2022-08-01' AND C1.START_DATE <= '2022-10-31'
GROUP BY MONTH(C1.START_DATE), C1.CAR_ID
ORDER BY MONTH ASC, C1.CAR_ID DESC
;