-- 코드를 작성해주세요
SELECT FISH.ID, NAME.FISH_NAME, FISH.LENGTH
FROM FISH_INFO FISH
JOIN FISH_NAME_INFO NAME
    ON FISH.FISH_TYPE = NAME.FISH_TYPE
    JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS "MAX_LENGTH"
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) LENGTH
    ON FISH.FISH_TYPE = LENGTH.FISH_TYPE
    WHERE FISH.LENGTH = LENGTH.MAX_LENGTH
    ORDER BY FISH.ID ASC;
    