SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G 
JOIN HR_EMPLOYEES E 
ON G.EMP_NO = E.EMP_NO 
WHERE G.EMP_NO = (
    SELECT EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
) 
GROUP BY E.EMP_NO
;